# -*- coding: utf-8 -*-
"""ex wiki python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jHiow1Kq-w2Pj6qmxZ15Z-VGD-CFV_xB

1
"""

print('alo mundo')

"""2"""

numero = input('escolha um numero:')
print('o numero escolhido foi:' , numero)

"""3"""

numero1 = input('escolha um numero:')
numero2 = input('escolha outro numero:')
print('a soma dos seus numeros sao:' , int(numero1) + int(numero2))

"""4"""

nota1 = input('1 bimestre:')
nota2 = input('2 bimestre:')
nota3 = input('3 bimestre:')
nota4 = input('4 bimestre:')
print("media:" , (int(nota1) + int(nota2) +int(nota3) + int(nota4)) /4)

"""5"""

medida_m = input('medida em metros:')
print('medida em cm:' , int(medida_m) * 100)

"""6"""

raio = input('raio do circulo:')
print('a area é:' , (int(raio) * int(raio)) * 3.14)

"""7"""

lado = input('lado do quadrado:')
print('o dobro da area é:' , (int(lado) * int(lado)) * 2)

"""8"""

valorhora = input('quanto vc recebe por hora?')
horames = input('qual sua carga horaria?')
print('seu salario é:' , int(valorhora) * int(horames))

"""9"""

temperaturaf = input('temperatura em fahrenheit:')
print('o valor em celsius é:' , 5 * ((int(temperaturaf) -32) / 9))

"""10"""

temperaturac = input('temperatura em celsius:')
print('o valor em fahrenheit é:' , (int(temperaturac) * 1.8) + 32)

"""11"""

numero1 = input('numero 1:')
numero2 = input('numero 2:')
numero3 = input('numero 3:')
print(int(numero1) *2 + int(numero2) /2)
print(int(numero1) * 3 + int(numero3))
print(int(numero3) * int(numero3) * int(numero3))

"""12 e 13"""

sexo = input('qual seu sexo?')
altura = float(input('qual sua altura?'))
if sexo == 'masculino':
  print((72.7*(altura)) - 58)
else:
  print((62.1*(altura)) - 44.7)

"""14"""

peso = input('peso dos peixes:')
if int(peso) < 50:
 print('sem multa')
else: 
  print('valor da multa:' , (int(peso) - 50) * 4)

"""15

"""

horas = int(input('horas trabalhadas:'))
valor_hora = int(input('valor por hora trabalhada:'))
salario_bruto = horas * valor_hora
ir = salario_bruto * 0.11
inss = salario_bruto * 0.08
sindicato = salario_bruto * 0.05
salario_liquido = salario_bruto - ir - inss - sindicato
print("salario bruto:" , salario_bruto)
print("ir:" , ir)
print("inss:" , inss)
print("sindicato:" , sindicato)
print("salario liquido:" , salario_liquido)

"""16"""

metros_quadrado = int(input("quantos metros quadrados vao ser pintados:"))
litros_usados = metros_quadrado /3
lata = litros_usados / 18
preço = round(lata) * 80 

print("serao usadas" , round(lata + 0.5) , "latas" , "e o preço e:" , preço)

"""17

Faça um Programa para uma loja de tintas. O programa deverá pedir o tamanho em metros quadrados da área a ser pintada. Considere que a cobertura da tinta é de 1 litro para cada 6 metros quadrados e que a tinta é vendida em latas de 18 litros, que custam R$ 80,00 ou em galoes de 3,6 litros que custam R$ 25,00
Informe ao usuário as quantidades de tinta a serem compradas e os respectivos preços em 3 situações:
comprar apenas latas de 18 litros;
comprar apenas galões de 3,6 litros;
misturar latas e galões, de forma que o desperdício de tinta seja menor. Acrescente 10% de folga e sempre arredonde os valores para cima, isto é, considere latas cheias.
"""

metros_quadrados = int(input("quantos metros quadrados vao ser pintados:"))
litros_usados = (metros_quadrados / 6) * 1.1
latas = litros_usados / 18
galao = litros_usados / 3.6
resto_galao = (litros_usados % 18) / 3.6
valor_rgalao = round(resto_galao) * 25
valor_lata = round(latas)  * 80
valor_galao = round(galao) * 1.1 * 25

print('o valor comprando apenas latas é:' , valor_lata , 'e serão usadas:' , round(latas + 0.5), 'latas')
print('o valor comprando apenas galoes é:' , valor_galao , 'e serão usados:' , round(galao + 0.5), 'galoes')
print('o valor comprando latas e galoes é:' , valor_lata + valor_rgalao ,  'e serão usados:' , round(latas + 0.5) , 'latas e' , round(resto_galao + 0.5) , 'galoes')

"""18 Faça um programa que peça o tamanho de um arquivo para download (em MB) e a velocidade de um link de Internet (em Mbps), calcule e informe o tempo aproximado de download do arquivo usando este link (em minutos).

"""

tamanho = float(input('qual o tamanho do arquivo para dowload (em MB)?'))
velo = float(input('qual a velocidade da sua internet (em Mbps)?'))
tempo = tamanho/velo
print(tempo)
print('o tempo aproximado de dowload é:' , round(tempo /60 , 2) , 'minutos')