# -*- coding: utf-8 -*-
"""ex wiki python 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V2bI2aW0OipPBsRtOuBiXoggXSrpacJV

1 Faça um Programa que leia um vetor de 5 números inteiros e mostre-os.
"""

lista = [1, 2, 3 , 4, 5]

print(lista)

"""2 Faça um Programa que leia um vetor de 10 números reais e mostre-os na ordem inversa"""

lista = [1, 2, 3 , 4, 5, 6, 7, 8, 9, 10]

lista.reverse()

print(lista)

"""3 Faça um Programa que leia 4 notas, mostre as notas e a média na tela.

"""

lista_notas = []

for nota in range(4):
  lista_notas.append(int(input('digite uma nota:')))

media = 0 
for nota in lista_notas:
  media += nota
print(media / len(lista_notas))

"""4 Faça um Programa que leia um vetor de 10 caracteres, e diga quantas consoantes foram lidas. Imprima as consoantes."""

lista_letras = []

for i in range(10):
  lista_letras.append(input('digite uma letra:'))

for letra in lista_letras:
  print(letra)